### ISSUE TITLE
I encountered this, would you please  help?

### ISSUE THREAD

**Issue by Jailman** [d0p3t/SerpentCloneyGameAgentPlugin#3]
When I started the game in anaconda console with serpent, it indicated this:
Using TensorFlow backend.
Traceback (most recent call last):
  File "c:\users\jailman\anaconda3\envs\serpent\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jailman\anaconda3\envs\serpent\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jailman\Anaconda3\envs\serpent\Scripts\serpent.exe\__main__.py", line 9, in <module>
  File "c:\users\jailman\anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 48, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "c:\users\jailman\anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 238, in play
    game.play(game_agent_class_name=game_agent_name, frame_handler=frame_handler)
  File "c:\users\jailman\anaconda3\envs\serpent\lib\site-packages\serpent\game.py", line 186, in play
    raise e
  File "c:\users\jailman\anaconda3\envs\serpent\lib\site-packages\serpent\game.py", line 177, in play
    game_agent.on_game_frame(game_frame, frame_handler=frame_handler, **kwargs)
  File "c:\users\jailman\anaconda3\envs\serpent\lib\site-packages\serpent\game_agent.py", line 89, in on_game_frame
    print(frame_handler(game_frame, **kwargs))
TypeError: 'NoneType' object is not callable

**Comment by d0p3t** [comment]
As far as I remember (it's been a while) this game agent is currently broken because I was trying out some things.

I'm not working on this game agent anymore, sorry.

Make sure the game is running with `serpent launch Cloney` and then run the game agent. Only advice I can give

**Comment by Jailman** [comment]
thanks for the advice
